### PR TITLE
Fix handling of where clauses, lifetimes, and const generics

### PR DESCRIPTION
**Pull request by MingweiSamuel**
And adds test for them to 03-generics.

Also updates the stderr messages for the failing tests.

### CODE REVIEW

**Comment by MingweiSamuel** [comment]
Fixes #12

**Review by jmg-duarte — CHANGES_REQUESTED** [review]
Great job! I just ask you to split the test case into several, smaller ones.

**Comment by jmg-duarte** [comment]
Good job, thank you so much for your contribution @MingweiSamuel!

**Comment by MingweiSamuel** [comment]
Thanks for this great library :D

**Pull request merged**
